name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          # Remove cache option until we have a lock file
          # cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint
        continue-on-error: true  # Allow the workflow to continue even if linting fails

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build 